// 自动生成:node scripts/gen-static-imports.mjs 1.6.0(2026-10-06),勿手改
// antdv-next@1.6.0 依赖树的 esm.sh 托管清单(从 genImportMap 暴露的入口沿模块图 BFS 得出):
//   - 版本号仅作回退值;运行时按所选 antdv-next 版本重新解析直接依赖并覆盖(resolveAntdvDeps)
//   - 重新生成:pnpm gen:imports(取当前 antdv-next latest);CI 校验:pnpm verify:imports
//   - legacy 回退模式(?resolver=legacy)用的是已冻结的 static-imports.ts,与本文件无关

/** Tier2:经裸导入引用共享单例(vue/@antdv-next/cssinjs/antdv-next)的包,
 *  由 esm.sh ?external= 服务;sub 为需显式登记的公开/深子路径(根条目恒有) */
export const ESM_PACKAGES: Record<string, { v: string; sub?: string[] }> = {
  '@antdv-next/cssinjs': { v: '1.1.0', sub: ['cssinjs-utils'] },
  '@v-c/cascader': { v: '1.1.6' },
  '@v-c/checkbox': { v: '1.0.2' },
  '@v-c/collapse': { v: '1.0.2' },
  '@v-c/color-picker': { v: '1.0.6' },
  '@v-c/dialog': { v: '1.2.1' },
  '@v-c/drawer': { v: '1.0.8' },
  '@v-c/dropdown': { v: '1.1.1' },
  '@v-c/image': { v: '1.1.2' },
  '@v-c/input': { v: '1.1.2' },
  '@v-c/input-number': { v: '1.1.1' },
  '@v-c/listy': { v: '1.2.0' },
  '@v-c/mentions': { v: '1.2.3' },
  '@v-c/menu': { v: '1.4.2' },
  '@v-c/mutate-observer': { v: '1.0.3' },
  '@v-c/notification': { v: '2.0.5' },
  '@v-c/overflow': { v: '1.1.2' },
  '@v-c/pagination': { v: '1.1.2', sub: ['locale/en_US', 'locale/zh_CN'] },
  '@v-c/picker': { v: '1.5.2', sub: ['generate/dayjs', 'locale/en_US'] },
  '@v-c/portal': { v: '1.0.8' },
  '@v-c/progress': { v: '1.0.3' },
  '@v-c/qrcode': { v: '1.0.1' },
  '@v-c/rate': { v: '1.0.1' },
  '@v-c/resize-observer': { v: '1.1.3' },
  '@v-c/segmented': { v: '1.0.6' },
  '@v-c/select': { v: '1.2.8' },
  '@v-c/slick': { v: '1.0.2' },
  '@v-c/slider': { v: '1.1.4' },
  '@v-c/steps': { v: '1.0.3', sub: ['dist/UnstableContext.js'] },
  '@v-c/switch': { v: '1.0.1' },
  '@v-c/table': { v: '1.3.4' },
  '@v-c/tabs': { v: '1.4.2' },
  '@v-c/textarea': { v: '1.1.1' },
  '@v-c/tooltip': { v: '1.1.4' },
  '@v-c/tour': { v: '1.1.2' },
  '@v-c/tree': { v: '1.2.3' },
  '@v-c/tree-select': { v: '1.1.3' },
  '@v-c/trigger': { v: '1.1.6' },
  '@v-c/upload': { v: '1.1.0' },
  '@v-c/util': {
    v: '1.3.2',
    sub: [
      'dist/Children/isFragment',
      'dist/Children/toArray',
      'dist/Dom/canUseDom',
      'dist/Dom/class',
      'dist/Dom/contains',
      'dist/Dom/dynamicCSS',
      'dist/Dom/findDOMNode',
      'dist/Dom/focus',
      'dist/Dom/focusBoundary',
      'dist/Dom/isVisible',
      'dist/Dom/shadow',
      'dist/Dom/styleChecker',
      'dist/KeyCode',
      'dist/RenderComponent',
      'dist/getScrollBarSize',
      'dist/hooks/useDelayState',
      'dist/hooks/useEvent',
      'dist/hooks/useId',
      'dist/hooks/useLayoutEffect',
      'dist/hooks/useMemo',
      'dist/hooks/useMergedState',
      'dist/isEqual',
      'dist/isMobile',
      'dist/omit',
      'dist/pickAttrs',
      'dist/pickDefined',
      'dist/props-util',
      'dist/raf',
      'dist/utils/get',
      'dist/utils/omit',
      'dist/utils/set',
      'dist/utils/transition',
      'dist/vnode',
      'dist/vueuse/unref-element',
      'dist/warning',
    ],
  },
  '@v-c/virtual-list': { v: '1.1.2' },
  '@vueuse/core': { v: '14.4.0' },
  '@vueuse/shared': { v: '14.4.0' },
}

/** Tier3:不引用共享单例的叶子包,import map 登记根 + 尾斜杠前缀 key,
 *  任意子路径拼写(含 .js 后缀漂移)由 esm.sh 运行时解析 */
export const LEAF_PACKAGES: Record<string, string> = {
  '@ant-design/colors': '8.0.1',
  '@ant-design/fast-color': '3.0.1',
  '@emotion/hash': '0.8.0',
  '@emotion/unitless': '0.7.5',
  '@v-c/async-validator': '1.0.2',
  '@v-c/mini-decimal': '1.0.1',
  'compute-scroll-into-view': '3.1.1',
  dayjs: '1.11.23',
  'es-toolkit': '1.52.0',
  'resize-observer-polyfill': '1.5.1',
  'scroll-into-view-if-needed': '3.1.0',
  stylis: '4.4.0',
  'throttle-debounce': '5.0.2',
}

/** Tier1 补充:raw dist 单文件 bundle(esm.sh 会走 exports 主入口逐文件请求,不可搬) */
export const RAW_PACKAGES: Record<string, { v: string; path: string }> = {
  '@antdv-next/icons': { v: '1.1.2', path: '/dist/antd-icons.esm.js' },
}
