// 自动生成:node scripts/gen-static-imports.mjs 1.5.3(2026-09-01),勿手改
// antdv-next@1.5.3 依赖树(共 104 个 specifier)的运行时可达裸导入枚举:
//   - 来源:从 genImportMap 暴露的 antdv-next 入口沿模块图 BFS,子路径经 exports map(import 条件)解析
//   - 规则:有浏览器可用 ESM 构建的用原始文件 URL(经 import map 统一 vue 实例);
//     无 ESM 构建的(ESM_IMPORTS)退化为 jsdelivr +esm 转换,CDN 切到 unpkg 时走 esm.sh
// 重新生成:pnpm gen:imports(取当前 antdv-next latest);CI 校验:pnpm verify:imports
export const STATIC_IMPORTS: Record<string, string> = {
  '@ant-design/colors': '/@ant-design/colors@8.0.1/+esm',
  '@ant-design/fast-color': '/@ant-design/fast-color@3.0.1/+esm',
  '@antdv-next/cssinjs': '/@antdv-next/cssinjs@1.0.6/dist/index.js',
  '@antdv-next/cssinjs/cssinjs-utils':
    '/@antdv-next/cssinjs@1.0.6/dist/cssinjs-utils/index.js',
  '@antdv-next/icons': '/@antdv-next/icons@1.1.2/dist/antd-icons.esm.js',
  '@emotion/hash': '/@emotion/hash@0.8.0/dist/hash.esm.js',
  '@emotion/unitless': '/@emotion/unitless@0.7.5/dist/unitless.esm.js',
  '@v-c/async-validator': '/@v-c/async-validator@1.0.2/dist/index.js',
  '@v-c/cascader': '/@v-c/cascader@1.1.3/dist/index.js',
  '@v-c/checkbox': '/@v-c/checkbox@1.0.1/dist/index.js',
  '@v-c/collapse': '/@v-c/collapse@1.0.1/dist/index.js',
  '@v-c/color-picker': '/@v-c/color-picker@1.0.6/dist/index.js',
  '@v-c/dialog': '/@v-c/dialog@1.2.0/dist/index.js',
  '@v-c/drawer': '/@v-c/drawer@1.0.7/dist/index.js',
  '@v-c/dropdown': '/@v-c/dropdown@1.0.5/dist/index.js',
  '@v-c/image': '/@v-c/image@1.1.0/dist/index.js',
  '@v-c/input': '/@v-c/input@1.1.1/dist/index.js',
  '@v-c/input-number': '/@v-c/input-number@1.0.7/dist/index.js',
  '@v-c/listy': '/@v-c/listy@1.0.2/dist/index.js',
  '@v-c/mentions': '/@v-c/mentions@1.2.0/dist/index.js',
  '@v-c/menu': '/@v-c/menu@1.3.2/dist/index.js',
  '@v-c/mini-decimal': '/@v-c/mini-decimal@1.0.1/dist/index.js',
  '@v-c/mutate-observer': '/@v-c/mutate-observer@1.0.2/dist/index.js',
  '@v-c/notification': '/@v-c/notification@2.0.3/dist/index.js',
  '@v-c/overflow': '/@v-c/overflow@1.1.1/dist/index.js',
  '@v-c/pagination': '/@v-c/pagination@1.1.1/dist/index.js',
  '@v-c/pagination/locale/en_US': '/@v-c/pagination@1.1.1/dist/locale/en_US.js',
  '@v-c/pagination/locale/zh_CN': '/@v-c/pagination@1.1.1/dist/locale/zh_CN.js',
  '@v-c/picker': '/@v-c/picker@1.3.2/dist/index.js',
  '@v-c/picker/generate/dayjs': '/@v-c/picker@1.3.2/dist/generate/dayjs.js',
  '@v-c/picker/locale/en_US': '/@v-c/picker@1.3.2/dist/locale/en_US.js',
  '@v-c/portal': '/@v-c/portal@1.0.8/dist/index.js',
  '@v-c/progress': '/@v-c/progress@1.0.2/dist/index.js',
  '@v-c/qrcode': '/@v-c/qrcode@1.0.1/dist/index.js',
  '@v-c/rate': '/@v-c/rate@1.0.1/dist/index.js',
  '@v-c/resize-observer': '/@v-c/resize-observer@1.1.3/dist/index.js',
  '@v-c/segmented': '/@v-c/segmented@1.0.5/dist/index.js',
  '@v-c/select': '/@v-c/select@1.2.5/dist/index.js',
  '@v-c/slick': '/@v-c/slick@1.0.2/dist/index.js',
  '@v-c/slider': '/@v-c/slider@1.1.1/dist/index.js',
  '@v-c/steps': '/@v-c/steps@1.0.1/dist/index.js',
  '@v-c/steps/dist/UnstableContext.js':
    '/@v-c/steps@1.0.1/dist/UnstableContext.js',
  '@v-c/switch': '/@v-c/switch@1.0.1/dist/index.js',
  '@v-c/table': '/@v-c/table@1.2.1/dist/index.js',
  '@v-c/tabs': '/@v-c/tabs@1.3.0/dist/index.js',
  '@v-c/textarea': '/@v-c/textarea@1.1.0/dist/index.js',
  '@v-c/tooltip': '/@v-c/tooltip@1.1.1/dist/index.js',
  '@v-c/tour': '/@v-c/tour@1.1.1/dist/index.js',
  '@v-c/tree': '/@v-c/tree@1.2.1/dist/index.js',
  '@v-c/tree-select': '/@v-c/tree-select@1.1.2/dist/index.js',
  '@v-c/trigger': '/@v-c/trigger@1.1.1/dist/index.js',
  '@v-c/upload': '/@v-c/upload@1.0.0/dist/index.js',
  '@v-c/util': '/@v-c/util@1.1.0/dist/index.js',
  '@v-c/util/dist/Children/isFragment':
    '/@v-c/util@1.1.0/dist/Children/isFragment.js',
  '@v-c/util/dist/Children/toArray':
    '/@v-c/util@1.1.0/dist/Children/toArray.js',
  '@v-c/util/dist/Dom/canUseDom': '/@v-c/util@1.1.0/dist/Dom/canUseDom.js',
  '@v-c/util/dist/Dom/class': '/@v-c/util@1.1.0/dist/Dom/class.js',
  '@v-c/util/dist/Dom/contains': '/@v-c/util@1.1.0/dist/Dom/contains.js',
  '@v-c/util/dist/Dom/dynamicCSS': '/@v-c/util@1.1.0/dist/Dom/dynamicCSS.js',
  '@v-c/util/dist/Dom/findDOMNode': '/@v-c/util@1.1.0/dist/Dom/findDOMNode.js',
  '@v-c/util/dist/Dom/focus': '/@v-c/util@1.1.0/dist/Dom/focus.js',
  '@v-c/util/dist/Dom/focusBoundary':
    '/@v-c/util@1.1.0/dist/Dom/focusBoundary.js',
  '@v-c/util/dist/Dom/isVisible': '/@v-c/util@1.1.0/dist/Dom/isVisible.js',
  '@v-c/util/dist/Dom/shadow': '/@v-c/util@1.1.0/dist/Dom/shadow.js',
  '@v-c/util/dist/Dom/styleChecker':
    '/@v-c/util@1.1.0/dist/Dom/styleChecker.js',
  '@v-c/util/dist/KeyCode': '/@v-c/util@1.1.0/dist/KeyCode.js',
  '@v-c/util/dist/RenderComponent': '/@v-c/util@1.1.0/dist/RenderComponent.js',
  '@v-c/util/dist/getScrollBarSize':
    '/@v-c/util@1.1.0/dist/getScrollBarSize.js',
  '@v-c/util/dist/hooks/useDelayState':
    '/@v-c/util@1.1.0/dist/hooks/useDelayState.js',
  '@v-c/util/dist/hooks/useEvent': '/@v-c/util@1.1.0/dist/hooks/useEvent.js',
  '@v-c/util/dist/hooks/useId': '/@v-c/util@1.1.0/dist/hooks/useId.js',
  '@v-c/util/dist/hooks/useLayoutEffect':
    '/@v-c/util@1.1.0/dist/hooks/useLayoutEffect.js',
  '@v-c/util/dist/hooks/useMemo': '/@v-c/util@1.1.0/dist/hooks/useMemo.js',
  '@v-c/util/dist/hooks/useMergedState':
    '/@v-c/util@1.1.0/dist/hooks/useMergedState.js',
  '@v-c/util/dist/isEqual': '/@v-c/util@1.1.0/dist/isEqual.js',
  '@v-c/util/dist/isMobile': '/@v-c/util@1.1.0/dist/isMobile.js',
  '@v-c/util/dist/omit': '/@v-c/util@1.1.0/dist/omit.js',
  '@v-c/util/dist/pickAttrs': '/@v-c/util@1.1.0/dist/pickAttrs.js',
  '@v-c/util/dist/props-util': '/@v-c/util@1.1.0/dist/props-util/index.js',
  '@v-c/util/dist/raf': '/@v-c/util@1.1.0/dist/raf.js',
  '@v-c/util/dist/utils/get': '/@v-c/util@1.1.0/dist/utils/get.js',
  '@v-c/util/dist/utils/omit': '/@v-c/util@1.1.0/dist/utils/omit.js',
  '@v-c/util/dist/utils/set': '/@v-c/util@1.1.0/dist/utils/set.js',
  '@v-c/util/dist/utils/transition':
    '/@v-c/util@1.1.0/dist/utils/transition.js',
  '@v-c/util/dist/vnode': '/@v-c/util@1.1.0/dist/vnode.js',
  '@v-c/util/dist/vueuse/unref-element':
    '/@v-c/util@1.1.0/dist/vueuse/unref-element.js',
  '@v-c/util/dist/warning': '/@v-c/util@1.1.0/dist/warning.js',
  '@v-c/virtual-list': '/@v-c/virtual-list@1.1.1/dist/index.js',
  '@vueuse/core': '/@vueuse/core@14.4.0/dist/index.js',
  '@vueuse/shared': '/@vueuse/shared@14.4.0/dist/index.js',
  'compute-scroll-into-view': '/compute-scroll-into-view@3.1.1/dist/index.js',
  dayjs: '/dayjs@1.11.23/+esm',
  'dayjs/plugin/advancedFormat': '/dayjs@1.11.23/plugin/advancedFormat/+esm',
  'dayjs/plugin/customParseFormat':
    '/dayjs@1.11.23/plugin/customParseFormat/+esm',
  'dayjs/plugin/localeData': '/dayjs@1.11.23/plugin/localeData/+esm',
  'dayjs/plugin/weekOfYear': '/dayjs@1.11.23/plugin/weekOfYear/+esm',
  'dayjs/plugin/weekYear': '/dayjs@1.11.23/plugin/weekYear/+esm',
  'dayjs/plugin/weekday': '/dayjs@1.11.23/plugin/weekday/+esm',
  'es-toolkit': '/es-toolkit@1.50.0/dist/index.mjs',
  'es-toolkit/compat': '/es-toolkit@1.50.0/dist/compat/index.mjs',
  'resize-observer-polyfill':
    '/resize-observer-polyfill@1.5.1/dist/ResizeObserver.es.js',
  'scroll-into-view-if-needed':
    '/scroll-into-view-if-needed@3.1.0/dist/index.js',
  stylis: '/stylis@4.4.0/index.js',
  'throttle-debounce': '/throttle-debounce@5.0.2/esm/index.js',
}

/** 需要 jsdelivr +esm 转换的 specifier(unpkg 不支持,CDN 切到 unpkg 时从 map 跳过) */
export const ESM_IMPORTS: string[] = [
  '@ant-design/colors',
  '@ant-design/fast-color',
  'dayjs',
  'dayjs/plugin/advancedFormat',
  'dayjs/plugin/customParseFormat',
  'dayjs/plugin/localeData',
  'dayjs/plugin/weekOfYear',
  'dayjs/plugin/weekYear',
  'dayjs/plugin/weekday',
]
